// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqL4C3lPc0GeviW6hmgzB4Ke8nSgCiG8Q',
    appId: '1:817138382486:web:8ad998ab1ddb2283b6f4b7',
    messagingSenderId: '817138382486',
    projectId: 'monitoring-gas-424e5',
    authDomain: 'monitoring-gas-424e5.firebaseapp.com',
    storageBucket: 'monitoring-gas-424e5.firebasestorage.app',
    measurementId: 'G-38EFH1MSBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYNxYAe2_UQY9UqQpudD2mRhD9WCzb20Q',
    appId: '1:817138382486:android:44ab0a3f42ca403ab6f4b7',
    messagingSenderId: '817138382486',
    projectId: 'monitoring-gas-424e5',
    storageBucket: 'monitoring-gas-424e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChAAztCKpEaF17tQsuS4G-aVdscTP9z-E',
    appId: '1:817138382486:ios:e478037b2d784b88b6f4b7',
    messagingSenderId: '817138382486',
    projectId: 'monitoring-gas-424e5',
    storageBucket: 'monitoring-gas-424e5.firebasestorage.app',
    iosBundleId: 'com.example.monitoringGas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChAAztCKpEaF17tQsuS4G-aVdscTP9z-E',
    appId: '1:817138382486:ios:e478037b2d784b88b6f4b7',
    messagingSenderId: '817138382486',
    projectId: 'monitoring-gas-424e5',
    storageBucket: 'monitoring-gas-424e5.firebasestorage.app',
    iosBundleId: 'com.example.monitoringGas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqL4C3lPc0GeviW6hmgzB4Ke8nSgCiG8Q',
    appId: '1:817138382486:web:1cf6086c362ad7aeb6f4b7',
    messagingSenderId: '817138382486',
    projectId: 'monitoring-gas-424e5',
    authDomain: 'monitoring-gas-424e5.firebaseapp.com',
    storageBucket: 'monitoring-gas-424e5.firebasestorage.app',
    measurementId: 'G-Z2HJTXEEYV',
  );
}
